### ISSUE TITLE
useCommitDistance is not appended for tagged commits

### ISSUE THREAD

**Issue by xeagle2** [jgitver/jgitver#37] opened 2018-01-06 12:08 UTC
In our case jgitver is used with <useCommitDistance>true</useCommitDistance> option.

When the project is new and has no any commits, but assigned to repository, using jgitver maven plugin translates the version 0 to 0.0.0-0-master, when 1 commit is added, the version becomes 0.0.0-1-master, 0.0.0-2-master, etc. It makes sense.

When a new tag is created  for example "0.0.1" on commit with the version <0.0.0-2-master> and new project build is performed, the project version gets translated to "0.0.1-master" without using the commit distance "0", even though "useCommitDistance" parameter is true. When more commits are added, the version becomes the right one such as 0.0.1-1-master, 0.0.1-2-master, etc.

The "0" distance should be added to the version on tagged commits to preserve the functional consistency of the behavior.

Thank you,

**Comment by McFoggy** [comment] 2018-01-09 08:19
@xeagle2 this was on purpose from the beginning to allow to compute correctly versions on tags.

If we change that it will mean that when adding a release tag, one cannot build directly from the current branch anymore but has to checkout the tag in a detached head in order to build the tag with the correct version. This could be seen has painfull even if it is _sensu stricto_ more correct.  
At the moment I am really not in favor of changing that behavior. Moreover #33 will probably let you do exactly what you want by defining your behavior as you want.

I would tend to close this issue as _expected behavior_, agree?

**Comment by xeagle2** [comment] 2018-01-09 08:36
@McFoggy, The version (major.minor.patch) is computed properly. You know I mention the qualifier which doesn't contain anything else except for branch name if it finds a tagged commit. 

So if someone decides to use commit distance as additional feature, why should it behave differently? It's a part of the qualifier like timestamp, etc which typically expected to be present on main stream builds. 

If someone wants to build a tag, probably it makes sense to fetch it to detached head to prepare release or something, but keep building the artifacts in branches with consistent qualifier pattern?

**Comment by McFoggy** [comment] 2018-01-09 09:11
@xeagle2 I perfectly understood what you were meaning. What I try to make you aware is that the described behavior was intended.

Given a project with `useCommitDistance` set to `true`, today tagging a commit with a release tag lead in a version using that tag without the distance.

![image](https://user-images.githubusercontent.com/1119660/34712365-e4bbc8b8-f522-11e7-984e-097505e0bbb4.png)

It was really intentionnal for me to set the distance qualifier only on commits not having an annotated tag to ease the CI/CD/release process.

Your behavior today is accessible if you use __lightweight__ tags, like described below

![image](https://user-images.githubusercontent.com/1119660/34713002-2386cc3a-f525-11e7-96f1-3f11c5d3bfd9.png)

#33 will for sure give you other possibilities.

**Comment by xeagle2** [comment] 2018-01-09 19:18
I understand that it was done intentionally. #33 should solve typically the task. I think this issue could be closed.

**Comment by McFoggy** [comment] 2018-11-03 09:03
non issue

**Closed by McFoggy** 2018-11-03 09:03 UTC
Labels: wontfix
