### ISSUE TITLE
Allow tag name pattern to be configurable

### ISSUE THREAD

**Issue by JohnWu-Pro** [jgitver/jgitver#7] opened 2016-06-30 14:03 UTC
For example, to allow the tag name to `optional_PREFIX` `VERSION` `optional_SUFFIX`. In Ant-match pattern, the tag name should be allowed as `*`, `PREFIX*`,`*SUFFIX`, or `PREFIX*SUFFIX`. And the version portion should match semver spec.

IMHO, There may be challenge of putting Ant pattern matching and regex matching in one run. The simplest way of implementing it is to do Ant pattern matching first to extract version in its entirety and perform regex matching next to parse version sections.

**Comment by JohnWu-Pro** [comment] 2016-06-30 14:11
This may overlapping with #6

**Comment by McFoggy** [comment] 2016-06-30 14:46
@JohnWu-Pro indeed it overlaps.

Duplicate of #6

**Closed by McFoggy** 2016-06-30 14:46 UTC
